apiVersion: apps/v1
kind: Deployment

metadata:
  name: docuhelper-auth-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docuhelper-auth
  template:
    metadata:
      labels:
        app: docuhelper-auth
    spec:
      containers:
        - name: docuhelper-auth-container
          image: docker.bmserver.org/docuhelper-auth:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: docuhelper-configmap-prod
---

apiVersion: v1
kind: Service

metadata:
  name: docuhelper-auth-service

spec:
  type: NodePort
  selector:
    app: docuhelper-auth
  ports:
    - protocol: TCP
      targetPort: 8081    # pod 포트
      port: 8081          # 서비스 내부 포트
      nodePort: 30002      # 서비스 외부 포트
