server:
  port: ${PORT:8081}

spring:
  application:
    name: docuhelper-auth
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:192.168.0.7}:${DB_PORT:5432}/docuhelper
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:password}
  security:
    jwt:
      secret: ${JWT_SECRET:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope: profile, email
