server:
  port: ${PORT:8081}

spring:
  application:
    name: docuhelper-auth
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:192.168.0.7}:${DB_PORT:5432}/${DB_SCHEMA:docuhelper} # schema ??? webflux? ???
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:password}
  security:
    jwt:
      secret: ${JWT_SECRET}
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope: profile, email
